### ISSUE TITLE
Readme not updated

### ISSUE THREAD

**Issue by hollensted** [bitbank2/BitBang_I2C#11]
The readme has some errors. Guess it was not updated:

I2CRead(uint8_t u8Address, uint8_t *pu8Data, int iLength);
I2CReadRegister(uint8_t iAddr, uint8_t u8Register, uint8_t *pData, int iLen);
I2CWrite(uint8_t iAddr, uint8_t *pData, int iLen);

,,missing the first argument.

**Comment by bitbank2** [comment]
fixed
