### ISSUE TITLE
Read & Write Examples

### ISSUE THREAD

**Issue by Jim-bee** [bitbank2/BitBang_I2C#28]
Hi can you please add in read and write example code for your library.

Thanks.

**Comment by bitbank2** [comment]
I agree it can use some examples. A good way to see how to use the API is to look at the discover devices code in the library itself. It uses both read and write functions:

https://github.com/bitbank2/BitBang_I2C/blob/3a4429da46c53b5e1144529f942ea61e21b56777/src/BitBang_I2C.cpp#L806
