### ISSUE TITLE
Fram Support

### ISSUE THREAD

**Issue by Jim-bee** [bitbank2/BitBang_I2C#29]
It is possible to add support for Fujitsu's MB85RC fram series (MB85RC128A for example).

Thanks,

**Comment by bitbank2** [comment]
Are you asking if I can add it to the list of devices recognized by the I2C_Detect function? After looking at the data sheet, I would say "no". The reason being that it doesn't have a "WHO_AM_I" register nor is there a non-destructive sequence to know if it's that FRAM chip. I would have to write data and read it back to know if it's that chip. That breaks my "non-destructive" test rule.
