### ISSUE TITLE
Init pulls SDA and SCL low

### ISSUE THREAD

**Issue by charlysan** [bitbank2/BitBang_I2C#34]
I see that `SDA` and `SCL` are being pulled low at initialization:

<img width="800" alt="image" src="https://github.com/user-attachments/assets/ca2b6b93-84c1-4906-b477-914d62728b9b">

And it is because of this:

<img width="743" alt="image" src="https://github.com/user-attachments/assets/970d7faf-d784-42d5-a2a1-d5f03a4b91a1">

Is there a reason why you pull the lines low before setting them as input?

The issue I have with this is that it injects this small 'glitch' into the bus when the microcontroller is being reset.

**Comment by bitbank2** [comment]
Yes, there's a reason. It's to create a "pull down" situation on some microcontrollers. With the output value set to low, when set as outputs, they will pull the line low. When set as inputs, the line will float high. This reduces the number of cycles it takes to switch between the 2 states.

**Comment by charlysan** [comment]
Do you think this could be configurable? (e.g., by passing an extra argument to `i2cInit()`). In my case, when using it with the ESP8266, this 'glitch' at initialization could interfere with other devices connected to the bus. For the moment, as a workaround, I'm using a fork where I removed those lines.

**Comment by bitbank2** [comment]
I am so busy with other projects that I don't have any spare cycles to work on this. I think it would be best to work from your fork if you need to make that change. If you can change it with a PR in a way which doesn't break existing projects, then I would accept it.

**Comment by charlysan** [comment]
Yes, of course, I will create a PR. Thanks.
