### ISSUE TITLE
2.2.2 not in Library Manager

### ISSUE THREAD

**Issue by arturo182** [bitbank2/BitBang_I2C#35]
Looks like you forgot to update the version in [the json file](https://github.com/bitbank2/BitBang_I2C/blob/master/library.properties#L2), and 2.2.2 is missing in the Library Manager :sweat_smile: 

![image](https://github.com/user-attachments/assets/4552b571-0f66-4a23-aff3-5fb033a5cb11)

**Comment by arturo182** [comment]
You can also see arduino scraper being confused here: https://downloads.arduino.cc/libraries/logs/github.com/bitbank2/BitBang_I2C/

**Comment by bitbank2** [comment]
Thanks for catching that - I'll correct it. Does anyone actually use this library? :)
