### ISSUE TITLE
Having trouble

### ISSUE THREAD

**Issue by GreyArea1966** [bitbank2/BitBang_I2C#7]
This used to work with my display but now seems not to. Same display works with the fullsize driver, so I assume it's just something I'm doing wrong.

Changed pins to 4 and 5 for SDA/SCL as I'm on an Arduino Uno, but just getting blank screen.

**Comment by bitbank2** [comment]
A4 != 4. You can specify the pins as port name + bit. For example - PORTB, bit 1 would be 0xb1. Pins A4 and A5 on the Uno can be specified as A4/A5 (they're macros), but if you just use a number, they are pins 18/19.

**Comment by bitbank2** [comment]
P.S., if you've connected your display to the A4/A5 lines on the Uno, set the pin numbers to -1 and enable hardware I2C.

**Comment by GreyArea1966** [comment]
Working now, the -1 and enabling hardware trick worked, many thanks!
