### ISSUE TITLE
New Example request: EEPROM

### ISSUE THREAD

**Issue by vslinuxdotnet** [bitbank2/BitBang_I2C#8]
Hello,
Can you please write some example to read and write from a eeprom 24CXX using BitBang_I2C?
I have some problems with the wire lib with: Wire.endTransmission() with no default I2C pins.
With your lib seams ok and no crash the I2c Transmission.
Thank You

**Comment by bitbank2** [comment]
It's already written in my rtc_eeprom library. Look here:

https://github.com/bitbank2/rtc_eeprom/blob/master/Arduino/rtc_eeprom.cpp
