### ISSUE TITLE
Implementing on a beaglebone black 

### ISSUE THREAD

**Issue by frank2597** [bitbank2/BitBang_I2C#9]
Hello, I was wondering if it would be possible to implement this for the beaglebone black which would act as a slave device to a raspberry pi which would act as the master?

**Comment by bitbank2** [comment]
I haven't implemented the I2C slave portion; it would probably be easier to adapt the Arduino I2C software slave library than start from scratch from mine. I think you only need the ability to have a pin change interrupt and the rest is pretty generic.
